### ISSUE TITLE
ORDER BY clause for API.

### ISSUE THREAD

**Issue by RohitKaushal7** [rohithill/nithp#7]
in case of fetching student results for entire college an application may require data in sorted order considering that the pagination in active on the api application will need to first fetch all the data and then sort at front end which will ruin the purpose of pagination.

required something like this..
/api/result/student?order=sgpi&dir=DESC

**Comment by rohithill** [comment]
It is nice idea. I will see to it.

**Comment by rohithill** [comment]
To anyone implementing this idea, this requires change in file [nith_result_api/swagger_api.py](https://github.com/rohithill/nithp/blob/62231ee47e806b5f3dbfb16544ef7ad5a4f43497/nith_result_api/swagger_api.py#L32) at referenced get_all_data function.

Currently pagination is cursor based which will give incorrect result if this feature is implemented naively. To implement this feature, knowledge of SQL and Python3 is required. Database used is sqlite3. Database schema is available [here](https://github.com/rohithill/nith_result_cli/blob/master/createDatabase.py).

**Comment by rohithill** [comment]
I have added this feature. Please check it.
