### ISSUE TITLE
[Feature] - Update a particular result

### ISSUE THREAD

**Issue by RohitKaushal7** [rohithill/nithp#8]
**Reason**
Results of some Students get updated dynamically ( on times we don't expect )
   eg - 
- students which have wrong result on official website which gets updated on request
- result of supplementary exams

**Solution / Feature**
Need an API endpoint [POST] to update a particular result by re scraping it from the official website.

**Comment by rohithill** [comment]
Currently the result is stored inside a git repo and the website is hosted on heroku which doesn't persist the changes made to the disk. So if updated result is written to the disk, it will be removed soon after. What will be the easiest way to solve this?

**Comment by RohitKaushal7** [comment]
the solution would be to use a different hosting for database like 
 - MongoDb Atlas ( free tier ) 
 - Heroku Postgress ( free tier )
 
but since the project is using SQLite , that is not possible. so maybe the dbms need to be changed.

but its fine - so basically to update any result the repository needs to be updated. so maybe no solution other than manually creating a commit with the updated result.

**Comment by RohitKaushal7** [comment]
@rohithill 
you can consider using Heroku Postgres for database, however Its free tier ( hobby dev ) has a limit of 10,000  rows max which will soon get filled up in 2-3 years 😅, but I think adding database will eliminate the need to commit result to repository every time and can be easily done by remotely executing the script through your website. 
just an opinion though.

**Comment by rohithill** [comment]
I'll check this out.
